### ISSUE TITLE
数据更新似乎不太及时

### ISSUE THREAD

**Issue by Ximu-Luya** [kmou424/resonance-mapperdata#1]
之前我尝试调用过几次接口，返回的上报数据都是在几小时之前。

目前接口返回似乎有鉴权了？

> {"error":"provided uuid is invalid"}

遂来咨询一下

**Comment by kmou424** [comment]
接口的时间是UTC +0时区。
接口现在是申请制的了，避免滥用，README还没有同步更新。

**Comment by Ximu-Luya** [comment]
@kmou424 好的明白了，等更新README。

不过话说为什么不用中国的+8时区，现在也没有外服吧（笑哭

**Comment by kmou424** [comment]
> @kmou424 好的明白了，等更新README。
> 
> 不过话说为什么不用中国的+8时区，现在也没有外服吧（笑哭

因为服务器时间默认UTC+0，我懒得调（（（

**Comment by Ximu-Luya** [comment]
hhh，好吧，python里的包应该支持一键配置时区吧……感觉成本应该不大？

**Comment by bw0963** [comment]
说不定国外也有不同时区的人要用呢（笑）
