### ISSUE TITLE
接口返回结果增加唯一标识符

### ISSUE THREAD

**Issue by Shaw-W** [kmou424/resonance-mapperdata#4]
希望接口种返回的数据新增id，跟goods_cities_mapper.json中的id一致就行（

**Comment by kmou424** [comment]
似乎并没有必要返回这种写死的数据，我甚至都想把baseprice删了来着（）

**Comment by Shaw-W** [comment]
base_price无所谓 主要是信息对应上 有个唯一主键无论是更新还是多表检索上都会更方便些

**Comment by kmou424** [comment]
已增加ID
